import { assetUrl } from '../asset-url.js'

const page3Asset = (path) => assetUrl(`assets/page3/${path}`)
const markerAspect = 1491 / 1055
const canvasWidth = 1.02
const canvasHeight = canvasWidth * 1.5

export const PAGE3_STATES = Object.freeze({
  HIDDEN: 'PAGE3_HIDDEN',
  LOADING: 'PAGE3_LOADING',
  READY: 'PAGE3_READY',
  STAGE_BUILDING: 'STAGE_BUILDING',
  WAIT_PEARL: 'WAIT_PEARL',
  PEARL_GUIDING: 'PEARL_GUIDING',
  WAIT_DRAGON: 'WAIT_DRAGON',
  DRAGON_DANCING: 'DRAGON_DANCING',
  WAIT_CLIMAX: 'WAIT_CLIMAX',
  IRONFLOWER_CLIMAX: 'IRONFLOWER_CLIMAX',
  CLOSING: 'CLOSING',
  END_OPTIONS: 'END_OPTIONS',
  REAL_VIDEO: 'REAL_VIDEO',
  COMPLETE: 'COMPLETE',
})

export const PAGE3_CONFIG = {
  targetIndex: 2,
  markerAspect,
  targets: assetUrl('assets/markers/targets.mind'),
  markerImage: assetUrl('assets/markers/marker-page3.png'),
  assets: {
    background: page3Asset('background/page3-bg-board.png'),
    floor: page3Asset('background/page3-floor-base.png'),
    cloudBack: page3Asset('clouds/page3-cloud-back.png'),
    cloudMiddle: page3Asset('clouds/page3-cloud-middle.png'),
    cloudFront: page3Asset('clouds/page3-cloud-front.png'),
    title: page3Asset('title/page3-title-fire-night.png'),
    stageBack: page3Asset('stage/page3-stage-back.png'),
    stageFront: page3Asset('stage/page3-stage-front.png'),
    stageLights: page3Asset('stage/page3-stage-lights.png'),
    drum: page3Asset('props/page3-drum-main.png'),
    pearl: page3Asset('props/page3-dragon-pearl.png'),
    dragonVideo: page3Asset('performance/page3-perf-dragon.webm'),
    ironflowerVideo: page3Asset('performance/page3-perf-ironflower.webm'),
    dragonBgm: page3Asset('audio/page3-bgm-dragon-dance.mp3'),
    climaxBgm: page3Asset('audio/page3-bgm-ambience.mp3'),
    drumSfx: page3Asset('audio/page3-sfx-drum-hit.mp3'),
    ironflowerSfx: page3Asset('audio/page3-sfx-ironflower.mp3'),
    realVideo: page3Asset('real-video/page3-real-performance.mp4'),
    realPoster: page3Asset('real-video/page3-real-poster.jpg'),
  },
  durations: {
    trackingStableMs: 500,
    initialSecondaryDelayMs: 300,
    stageBuildingMs: 3000,
    pearlGuidingMs: 3000,
    dragonDancingMs: 5000,
    climaxMs: 8000,
    closingMs: 3000,
    drumFeedbackMs: 400,
    rippleMs: 820,
    realCompletionFadeMs: 1000,
  },
  tracking: {
    noticeDelayMs: 3000,
    anchorHoldMs: 1500,
    positionLerp: 0.12,
    rotationSlerp: 0.1,
    scaleLerp: 0.15,
    positionDeadzone: 0.002,
    rotationDeadzoneDeg: 0.35,
    scaleDeadzone: 0.001,
    lostHoldDuration: 1500,
    recoverDuration: 300,
  },
  layout: {
    width: canvasWidth,
    height: canvasHeight,
    scenePosition: [0, 0, 0.012],
    sceneRotation: [0, 0, 0],
    drumPivot: { x: 0, y: -0.49, z: 0.075 },
    drumAssetOffset: { x: 0, y: 0.49, z: 0 },
    drumHotspot: { x: 0.5, y: 0.805, width: 0.38, height: 0.23 },
    pearlPivot: { x: 0, y: 0.035, z: 0.061 },
    pearlAssetOffset: { x: 0, y: -0.035, z: 0 },
    pearlPath: [
      { x: 0.16, y: 0.03 },
      { x: -0.22, y: 0.25 },
      { x: 0.02, y: -0.12 },
      { x: 0.28, y: 0.08 },
      { x: -0.19, y: 0.04 },
    ],
    stageSafeArea: { x: 0.08, y: 0.26, width: 0.84, height: 0.34 },
    dragonVideo: {
      position: [-0.12, -0.03, 0.052],
      width: 0.59,
      maxHeight: 0.44,
      entranceOffset: { x: -0.05, y: -0.035 },
    },
    ironflowerVideo: {
      position: [0.26, -0.015, 0.049],
      width: 0.36,
      maxHeight: 0.42,
    },
    stageLights: {
      position: [0, -0.015, 0.044],
      width: 0.36,
      height: 0.36,
    },
  },
  z: {
    background: 0,
    floor: 0.004,
    cloudBack: 0.009,
    cloudMiddle: 0.013,
    title: 0.017,
    stageBack: 0.021,
    lights: 0.027,
    ironflowerVideo: 0.033,
    dragonVideo: 0.036,
    cloudFront: 0.041,
    pearl: 0.047,
    stageFront: 0.054,
    drum: 0.062,
    effects: 0.071,
  },
  renderOrder: {
    background: 300,
    floor: 301,
    cloudBack: 302,
    cloudMiddle: 303,
    title: 304,
    stageBack: 310,
    lights: 311,
    ironflowerVideo: 312,
    dragonVideo: 313,
    cloudFront: 314,
    pearl: 315,
    stageFront: 320,
    drum: 325,
    effects: 330,
  },
  clouds: {
    back: { amplitudeX: 0.08, amplitudeY: 0, opacityMin: 0.3, opacityMax: 0.45, periodMs: 12000, phase: 0 },
    middle: { amplitudeX: -0.07, amplitudeY: 0.012, opacityMin: 0.35, opacityMax: 0.55, periodMs: 9000, phase: 1.7 },
    front: { amplitudeX: 0.06, amplitudeY: 0.03, opacityMin: 0.4, opacityMax: 0.6, periodMs: 7000, phase: 3.1 },
    climaxOpacityScale: 0.62,
  },
  drum: {
    idleScaleMin: 0.98,
    idleScaleMax: 1.02,
    idlePeriodMs: 2100,
    hitScales: [1, 0.92, 1.06, 1],
    hitStops: [0, 0.23, 0.58, 1],
    rippleCount: 3,
    rippleDelayMs: 100,
    rippleStartScale: 0.3,
    rippleEndScale: 2,
  },
  audio: {
    drumSfxVolume: 0.88,
    ironflowerSfxVolume: 0.78,
    dragonBgmVolume: 0.5,
    climaxBgmVolume: 0.58,
    fadeMs: 800,
  },
  particles: {
    low: 24,
    normal: 44,
    continuousRatePerSecond: 14,
    size: 0.018,
  },
  performance: {
    maxPixelRatio: 1.75,
    lowPowerConcurrency: 3,
    normalConcurrency: 4,
  },
}

export const PAGE3_IMAGE_ENTRIES = Object.freeze([
  ['page3-background-asset', 'background'],
  ['page3-floor-asset', 'floor'],
  ['page3-cloud-back-asset', 'cloudBack'],
  ['page3-cloud-middle-asset', 'cloudMiddle'],
  ['page3-cloud-front-asset', 'cloudFront'],
  ['page3-title-asset', 'title'],
  ['page3-stage-back-asset', 'stageBack'],
  ['page3-stage-front-asset', 'stageFront'],
  ['page3-stage-lights-asset', 'stageLights'],
  ['page3-drum-asset', 'drum'],
  ['page3-pearl-asset', 'pearl'],
])

export const PAGE3_CRITICAL_IMAGE_KEYS = Object.freeze([
  'background',
  'floor',
  'cloudBack',
  'cloudMiddle',
  'cloudFront',
  'title',
  'stageBack',
  'drum',
])
