import { assetUrl } from '../asset-url.js'

const page2Asset = (path) => assetUrl(`assets/page2/${path}`)

export const PAGE2_STATES = Object.freeze({
  HIDDEN: 'PAGE2_HIDDEN',
  GUIDE: 'PAGE2_GUIDE',
  OVERVIEW_ENTERING: 'PAGE2_OVERVIEW_ENTERING',
  OVERVIEW: 'PAGE2_OVERVIEW',
  MODEL_ENTERING: 'PAGE2_MODEL_ENTERING',
  MODEL: 'PAGE2_MODEL',
  COMPLETE: 'PAGE2_COMPLETE',
  TRACKING_LOST: 'PAGE2_TRACKING_LOST',
})

const spatial = {
  markerWidthMm: 148,
  cardDepthMm: 210,
  pngLayerCount: 21,
  backSafetyMm: 10,
  frontSafetyMm: 10,
  layerStepMm: 9.5,
  cardDepthUnit: 210 / 148,
  backSafetyUnit: 10 / 148,
  frontLimitUnit: 200 / 148,
  layerStepUnit: 9.5 / 148,
  depthScale: 1,
}

const layerKeys = [
  'title',
  'intro-line',
  'intro-text',
  'map-main',
  'map-text',
  'map-tongliang',
  'main-base',
  'main-ring',
  'main-scene',
  'main-sparks',
  'main-performers',
  'main-dancers',
  'main-dragon',
  'main-pearl',
  'types-title',
  'types-back',
  'types-mid',
  'types-front',
  'timeline-base',
  'timeline-nodes',
  'timeline-texts',
]

const mainDepthOffsetsMm = Object.freeze({
  'main-base': 0,
  'main-ring': 10,
  'main-scene': 22,
  'main-sparks': 35,
  'main-performers': 48,
  'main-dancers': 63,
  'main-dragon': 79,
  'main-pearl': 96,
})

const mainBaseDepthMm = spatial.backSafetyMm + layerKeys.indexOf('main-base') * spatial.layerStepMm

const layers = layerKeys.map((key, layerIndex) => {
  const defaultDepthMm = spatial.backSafetyMm + layerIndex * spatial.layerStepMm
  const depthMm = Object.prototype.hasOwnProperty.call(mainDepthOffsetsMm, key)
    ? mainBaseDepthMm + mainDepthOffsetsMm[key]
    : defaultDepthMm
  return {
    key,
    layerIndex,
    depthMm,
    depthUnit: (depthMm / spatial.markerWidthMm) * spatial.depthScale,
    renderOrder: 100 + layerIndex,
  }
})

export const PAGE2_CONFIG = {
  targetIndex: 1,
  overviewStableDelay: 250,
  overviewSequence: {
    moduleIntervalMs: 4000,
    mainAnimationStartDelayMs: 700,
    finalPromptDelayMs: 1500,
  },
  overviewDepthDirection: 'card-front',
  markerAspect: 210 / 148,
  markerImage: assetUrl('assets/markers/marker-02-craft.jpg'),
  targets: assetUrl('assets/markers/targets.mind'),
  spatial,
  layers,
  floorBase: {
    enabled: true,
    widthUnit: 1,
    depthUnit: 1.418918919,
    clearanceMm: 2,
    clearanceUnit: 0.013513514,
    initialClearanceUnit: 1 / 148,
    fadeDuration: 250,
    color: '#180806',
    opacity: 0.96,
    roughness: 1,
    metalness: 0,
    renderOrder: -100,
  },
  rescanReplay: {
    enabled: true,
    lostThresholdMs: 800,
    stableDelayMs: 180,
    replayFullEntrance: true,
  },
  mindar: {
    warmupTolerance: 2,
    missTolerance: 12,
    filterMinCF: 0.0007,
    filterBeta: 180,
  },
  assets: {
    background: page2Asset('background/page2-bg-full.png'),
    title: page2Asset('title/page2-title-group.png'),
    introDragon: page2Asset('intro/page2-intro-dragon-line.png.png'),
    introText: page2Asset('intro/page2-intro-text.png'),
    mapMain: page2Asset('map/page2-map-main.png'),
    mapText: page2Asset('map/page2-map-text.png'),
    mapTongliang: page2Asset('map/page2-map-tongliang.png'),
    mainBase: page2Asset('main-visual/page2-main-01-base-disc.png'),
    mainRing: page2Asset('main-visual/page2-main-02-rotating-ring.png'),
    mainScene: page2Asset('main-visual/page2-main-03-scene.png'),
    mainSparks: page2Asset('main-visual/page2-main-04-sparks.png'),
    mainPerformers: page2Asset('main-visual/page2-main-05-ironflower-performers.png'),
    mainDancers: page2Asset('main-visual/page2-main-06-dragon-dancers.png'),
    mainDragon: page2Asset('main-visual/page2-main-07-fire-dragon.png'),
    mainPearl: page2Asset('main-visual/page2-main-08-dragon-pearl.png'),
    typesTitle: page2Asset('types/page2-types-title.png'),
    typesBack: page2Asset('types/page2-types-row1-back.png'),
    typesMid: page2Asset('types/page2-types-row2-mid.png'),
    typesFront: page2Asset('types/page2-types-row3-front.png'),
    timelineBase: page2Asset('timeline/page2-timeline-base.png'),
    timelineNodes: page2Asset('timeline/page2-timeline-keynodes.png'),
    timelineTexts: page2Asset('timeline/page2-timeline-texts.png'),
    model: assetUrl('assets/model/fire-dragon.glb'),
  },
  trackingSmoothing: {
    positionLerp: 0.12,
    rotationSlerp: 0.1,
    scaleLerp: 0.15,
    positionDeadzone: 0.002,
    rotationDeadzoneDeg: 0.35,
    scaleDeadzone: 0.001,
    lostHoldDuration: 850,
    recoverDuration: 260,
  },
  background: {
    width: 1.02,
    height: 1.53,
    hingePosition: { x: 0, y: (210 / 148) / 2, z: 0.004 },
    startRotationX: 0,
    openAngle: 78,
    endRotationX: 78,
    openDuration: 900,
    surfaceZ: 0,
    overviewBrightness: 1,
    modelBrightness: 0.74,
  },
  overview: {
    initialDepthMm: 6,
    layerStagger: 70,
    layerDuration: 1050,
    exitDuration: 720,
    restoreDuration: 520,
  },
  map: {
    tongliangX: 0.6503125,
    tongliangY: 0.318125,
    tongliangOffsetX: 0,
    tongliangOffsetY: 0,
    tongliangGlowRadius: 0.022,
    tongliangPulseScale: 1.38,
    tongliangPulseDuration: 2600,
  },
  mainVisual: {
    ringCenterX: 0.3162,
    ringCenterY: 0.481,
    ringWidth: 0.5387,
    ringHeight: 0.5521,
    ringRotationSeconds: 40,
    pearlCenterX: 0.0365625,
    pearlCenterY: 0.435,
    pearlGlowRadius: 0.052,
    performersAmplitude: 0.0018,
    sceneAmplitude: 0.0008,
    dancersMotionAmplitude: 0.0048,
    dragonMotionAmplitude: 0.008,
    pearlMotionAmplitude: 0.0085,
    depthOffsetsMm: mainDepthOffsetsMm,
  },
  intro: {
    dragonGlowCenterX: 0.38125,
    dragonGlowCenterY: 0.252292,
    dragonGlowRadius: 0.115,
    pulseDuration: 3000,
  },
  types: {
    row1: { scale: 0.92, offsetY: 0.012 },
    row2: { scale: 0.98, offsetY: 0 },
    row3: { scale: 1.04, offsetY: -0.012 },
  },
  fireEntryHotspot: {
    x: 0.205,
    y: 0.461,
    width: 0.36,
    height: 0.24,
  },
  model: {
    centerDepthMm: 40.73,
    centerDepthUnit: 40.73 / 148,
    bottomClearanceMm: 4,
    bottomClearanceUnit: 4 / 148,
    backLimitMm: 20,
    backLimitUnit: 20 / 148,
    frontLimitMm: 190,
    frontLimitUnit: 190 / 148,
    targetWidthRatio: 2.55,
    defaultRotation: { x: 72, y: -8, z: -10 },
    entranceRotation: { x: 54, y: -18, z: -18 },
    entranceScale: 0.72,
    entranceRiseUnit: 0.48,
    minScale: 0.45,
    maxScale: 2.6,
    entranceDuration: 3300,
    dragSensitivity: 0.34,
    pinchSensitivity: 1,
  },
  particles: {
    low: 72,
    normal: 132,
    foregroundRatio: 0.18,
    middleRatio: 0.55,
    modelPeakTime: 0.58,
    sizeScale: 1.9,
  },
  performance: { maxPixelRatio: 1.75 },
  hotspots: { radius: 0.004, ringRadius: 0.0065, minimumViewed: 3 },
  progress: {
    completedKey: 'longmaiTongliang.page2.completed',
    viewedKey: 'longmaiTongliang.page2.viewedHotspots',
  },
}
