import { assetUrl } from '../asset-url.js'

const page2Asset = (path) => assetUrl(`assets/page2/${path}`)

export const PAGE2_STATES = Object.freeze({
  HIDDEN: 'PAGE2_HIDDEN',
  GUIDE: 'PAGE2_GUIDE',
  OVERVIEW_ENTERING: 'PAGE2_OVERVIEW_ENTERING',
  OVERVIEW: 'PAGE2_OVERVIEW',
  MODEL_ENTERING: 'PAGE2_MODEL_ENTERING',
  MODEL: 'PAGE2_MODEL',
  COMPLETE: 'PAGE2_COMPLETE',
  TRACKING_LOST: 'PAGE2_TRACKING_LOST',
})

const spatial = {
  markerWidthMm: 148,
  cardDepthMm: 210,
  pngLayerCount: 21,
  backSafetyMm: 10,
  frontSafetyMm: 10,
  layerStepMm: 9.5,
  cardDepthUnit: 210 / 148,
  backSafetyUnit: 10 / 148,
  frontLimitUnit: 200 / 148,
  layerStepUnit: 9.5 / 148,
  depthScale: 1,
}

const layerKeys = [
  'title',
  'intro-line',
  'intro-text',
  'map-main',
  'map-text',
  'map-tongliang',
  'main-base',
  'main-ring',
  'main-scene',
  'main-sparks',
  'main-performers',
  'main-dancers',
  'main-dragon',
  'main-pearl',
  'types-title',
  'types-back',
  'types-mid',
  'types-front',
  'timeline-base',
  'timeline-nodes',
  'timeline-texts',
]

const layers = layerKeys.map((key, layerIndex) => {
  const depthMm = spatial.backSafetyMm + layerIndex * spatial.layerStepMm
  return {
    key,
    layerIndex,
    depthMm,
    depthUnit: (depthMm / spatial.markerWidthMm) * spatial.depthScale,
    renderOrder: 100 + layerIndex,
  }
})

export const PAGE2_CONFIG = {
  targetIndex: 1,
  overviewStableDelay: 350,
  overviewEntranceDuration: 3200,
  overviewDepthDirection: 'card-front',
  markerAspect: 210 / 148,
  markerImage: assetUrl('assets/markers/marker-02-craft.jpg'),
  targets: assetUrl('assets/markers/targets.mind'),
  spatial,
  layers,
  assets: {
    background: page2Asset('background/page2-bg-full.png'),
    title: page2Asset('title/page2-title-group.png'),
    introDragon: page2Asset('intro/page2-intro-dragon-line.png.png'),
    introText: page2Asset('intro/page2-intro-text.png'),
    mapMain: page2Asset('map/page2-map-main.png'),
    mapText: page2Asset('map/page2-map-text.png'),
    mapTongliang: page2Asset('map/page2-map-tongliang.png'),
    mainBase: page2Asset('main-visual/page2-main-01-base-disc.png'),
    mainRing: page2Asset('main-visual/page2-main-02-rotating-ring.png'),
    mainScene: page2Asset('main-visual/page2-main-03-scene.png'),
    mainSparks: page2Asset('main-visual/page2-main-04-sparks.png'),
    mainPerformers: page2Asset('main-visual/page2-main-05-ironflower-performers.png'),
    mainDancers: page2Asset('main-visual/page2-main-06-dragon-dancers.png'),
    mainDragon: page2Asset('main-visual/page2-main-07-fire-dragon.png'),
    mainPearl: page2Asset('main-visual/page2-main-08-dragon-pearl.png'),
    typesTitle: page2Asset('types/page2-types-title.png'),
    typesBack: page2Asset('types/page2-types-row1-back.png'),
    typesMid: page2Asset('types/page2-types-row2-mid.png'),
    typesFront: page2Asset('types/page2-types-row3-front.png'),
    timelineBase: page2Asset('timeline/page2-timeline-base.png'),
    timelineNodes: page2Asset('timeline/page2-timeline-keynodes.png'),
    timelineTexts: page2Asset('timeline/page2-timeline-texts.png'),
    model: assetUrl('assets/model/fire-dragon.glb'),
  },
  trackingSmoothing: {
    positionLerp: 0.12,
    rotationSlerp: 0.1,
    scaleLerp: 0.15,
    positionDeadzone: 0.002,
    rotationDeadzoneDeg: 0.35,
    scaleDeadzone: 0.001,
    lostHoldDuration: 250,
    recoverDuration: 300,
  },
  background: {
    width: 1.02,
    height: 1.53,
    hingePosition: { x: 0, y: (210 / 148) / 2, z: 0.004 },
    startRotationX: 0,
    openAngle: 78,
    endRotationX: 78,
    openDuration: 900,
    surfaceZ: 0,
    overviewBrightness: 1,
    modelBrightness: 0.74,
  },
  overview: {
    initialDepthMm: 6,
    layerStagger: 70,
    layerDuration: 1050,
    exitDuration: 720,
    restoreDuration: 520,
  },
  map: {
    tongliangX: 0.783,
    tongliangY: 0.295,
    tongliangOffsetX: -0.03,
    tongliangOffsetY: 0,
    tongliangWidth: 0.02,
    tongliangHeight: 0.02,
    tongliangPulseScale: 1.52,
    tongliangPulseDuration: 2800,
  },
  mainVisual: {
    ringCenterX: 0.3162,
    ringCenterY: 0.481,
    ringWidth: 0.5387,
    ringHeight: 0.5521,
    ringRotationSeconds: 40,
    pearlCenterX: 0.316,
    pearlCenterY: 0.446,
    pearlWidth: 0.102,
    pearlHeight: 0.112,
    dancersAmplitude: 0.0025,
    dragonAmplitude: 0.004,
    pearlAmplitude: 0.005,
  },
  types: {
    row1: { scale: 0.92, offsetY: 0.012 },
    row2: { scale: 0.98, offsetY: 0 },
    row3: { scale: 1.04, offsetY: -0.012 },
  },
  fireEntryHotspot: {
    x: 0.205,
    y: 0.461,
    width: 0.36,
    height: 0.24,
  },
  model: {
    centerDepthMm: 105,
    centerDepthUnit: 105 / 148,
    bottomClearanceMm: 15,
    bottomClearanceUnit: 15 / 148,
    backLimitMm: 20,
    backLimitUnit: 20 / 148,
    frontLimitMm: 190,
    frontLimitUnit: 190 / 148,
    targetWidthRatio: 0.85,
    defaultRotation: { x: 0, y: 0, z: 0 },
    entranceRotation: { x: 5, y: -7, z: -4 },
    entranceScale: 0.9,
    entranceRiseUnit: 0.12,
    minScale: 0.65,
    maxScale: 1.45,
    entranceDuration: 3300,
    dragSensitivity: 0.34,
    pinchSensitivity: 1,
  },
  particles: {
    low: 72,
    normal: 132,
    foregroundRatio: 0.18,
    middleRatio: 0.55,
    modelPeakTime: 0.58,
  },
  performance: { maxPixelRatio: 1.75 },
  hotspots: { radius: 0.004, ringRadius: 0.0065, minimumViewed: 3 },
  progress: {
    completedKey: 'longmaiTongliang.page2.completed',
    viewedKey: 'longmaiTongliang.page2.viewedHotspots',
  },
}
