import { assetUrl } from '../asset-url.js'

const page2Asset = (path) => assetUrl(`assets/page2/${path}`)

export const PAGE2_STATES = Object.freeze({
  HIDDEN: 'PAGE2_HIDDEN',
  GUIDE: 'PAGE2_GUIDE',
  OVERVIEW_ENTERING: 'PAGE2_OVERVIEW_ENTERING',
  OVERVIEW: 'PAGE2_OVERVIEW',
  MODEL_ENTERING: 'PAGE2_MODEL_ENTERING',
  MODEL: 'PAGE2_MODEL',
  COMPLETE: 'PAGE2_COMPLETE',
  TRACKING_LOST: 'PAGE2_TRACKING_LOST',
})

export const PAGE2_CONFIG = {
  targetIndex: 1,
  overviewStableDelay: 420,
  overviewEntranceDuration: 2850,
  overviewDepthDirection: 'auto',
  markerAspect: 1491 / 1055,
  markerImage: assetUrl('assets/markers/marker-02-craft.jpg'),
  targets: assetUrl('assets/markers/targets.mind'),
  assets: {
    background: page2Asset('background/page2-bg-full.png'),
    title: page2Asset('title/page2-title-group.png'),
    introDragon: page2Asset('intro/page2-intro-dragon-line.png.png'),
    introText: page2Asset('intro/page2-intro-text.png'),
    mapMain: page2Asset('map/page2-map-main.png'),
    mapText: page2Asset('map/page2-map-text.png'),
    mapTongliang: page2Asset('map/page2-map-tongliang.png'),
    mainBase: page2Asset('main-visual/page2-main-01-base-disc.png'),
    mainRing: page2Asset('main-visual/page2-main-02-rotating-ring.png'),
    mainScene: page2Asset('main-visual/page2-main-03-scene.png'),
    mainSparks: page2Asset('main-visual/page2-main-04-sparks.png'),
    mainPerformers: page2Asset('main-visual/page2-main-05-ironflower-performers.png'),
    mainDancers: page2Asset('main-visual/page2-main-06-dragon-dancers.png'),
    mainDragon: page2Asset('main-visual/page2-main-07-fire-dragon.png'),
    mainPearl: page2Asset('main-visual/page2-main-08-dragon-pearl.png'),
    typesTitle: page2Asset('types/page2-types-title.png'),
    typesBack: page2Asset('types/page2-types-row1-back.png'),
    typesMid: page2Asset('types/page2-types-row2-mid.png'),
    typesFront: page2Asset('types/page2-types-row3-front.png'),
    timelineBase: page2Asset('timeline/page2-timeline-base.png'),
    timelineNodes: page2Asset('timeline/page2-timeline-keynodes.png'),
    timelineTexts: page2Asset('timeline/page2-timeline-texts.png'),
    model: assetUrl('assets/model/fire-dragon.glb'),
  },
  trackingSmoothing: {
    positionLerp: 0.12,
    rotationSlerp: 0.1,
    scaleLerp: 0.15,
    positionDeadzone: 0.002,
    rotationDeadzoneDeg: 0.35,
    scaleDeadzone: 0.001,
    lostHoldDuration: 250,
    recoverDuration: 300,
  },
  background: {
    width: 1.02,
    height: 1.53,
    hingePosition: { x: 0, y: 0.7065, z: 0.008 },
    startRotationX: 0,
    endRotationX: 72,
    openDuration: 900,
    surfaceZ: 0,
    overviewBrightness: 1,
    modelBrightness: 0.74,
  },
  overview: {
    exitDuration: 720,
    restoreDuration: 520,
  },
  title: {
    depth: 0.008,
  },
  intro: {
    depthDragonLine: 0.014,
    depthText: 0.02,
  },
  map: {
    depthMain: 0.012,
    depthText: 0.019,
    depthTongliang: 0.027,
    tongliangX: 0.783,
    tongliangY: 0.295,
    tongliangOffsetX: -0.018,
    tongliangOffsetY: 0,
    tongliangWidth: 0.02,
    tongliangHeight: 0.02,
    tongliangPulseScale: 1.52,
    tongliangPulseDuration: 2800,
  },
  mainVisual: {
    ringCenterX: 0.3162,
    ringCenterY: 0.481,
    ringWidth: 0.5387,
    ringHeight: 0.5521,
    ringRotationSeconds: 40,
    pearlCenterX: 0.316,
    pearlCenterY: 0.446,
    pearlWidth: 0.102,
    pearlHeight: 0.112,
    depths: {
      base: 0.018,
      ring: 0.026,
      scene: 0.034,
      sparks: 0.044,
      performers: 0.055,
      dancers: 0.067,
      dragon: 0.08,
      pearl: 0.094,
    },
    dancersAmplitude: 0.0025,
    dragonAmplitude: 0.004,
    pearlAmplitude: 0.005,
  },
  types: {
    depthTitle: 0.016,
    row1: { depth: 0.018, scale: 0.94, offsetY: 0.008 },
    row2: { depth: 0.038, scale: 0.98, offsetY: 0 },
    row3: { depth: 0.06, scale: 1.03, offsetY: -0.009 },
  },
  timeline: {
    depthBase: 0.012,
    depthKeyNodes: 0.021,
    depthTexts: 0.027,
  },
  fireEntryHotspot: {
    x: 0.205,
    y: 0.461,
    width: 0.36,
    height: 0.24,
  },
  model: {
    targetWidthRatio: 0.84,
    cardClearance: 0.035,
    backgroundClearance: 0.1,
    finalPosition: { x: 0, y: 0, z: 0.075 },
    entranceOffset: { x: 0, y: -0.12, z: -0.045 },
    defaultRotation: { x: 0, y: 0, z: 0 },
    entranceRotation: { x: 5, y: -7, z: -4 },
    entranceScale: 0.9,
    minScale: 0.65,
    maxScale: 1.8,
    entranceDuration: 3300,
    dragSensitivity: 0.34,
    pinchSensitivity: 1,
  },
  particles: {
    low: 72,
    normal: 132,
    foregroundRatio: 0.18,
    middleRatio: 0.55,
    modelPeakTime: 0.58,
  },
  performance: {
    maxPixelRatio: 1.75,
  },
  hotspots: {
    radius: 0.004,
    ringRadius: 0.0065,
    minimumViewed: 3,
  },
  progress: {
    completedKey: 'longmaiTongliang.page2.completed',
    viewedKey: 'longmaiTongliang.page2.viewedHotspots',
  },
}
